### ISSUE TITLE
Connecting to Temboo

### ISSUE THREAD

**Issue by mrcrocodile556** [alext-mkrs/edison-mon-sys#2]
Hi, 

Is there a breakdown steps on what to do after obtaining OAuth credentials and placing them into twitter_post.js?

**Comment by alext-mkrs** [comment]
Well, after you've got credentials, you just run the whole system according to readme instructions and when motion is detected, there will be a twit about that.

**Comment by mrcrocodile556** [comment]
Thank you, I am actually doing a project on motion detection following this tutorial: [https://communities.intel.com/docs/DOC-23972](url) 
This is similar to yours am i right?

Following this tutorial (assuming that i did not come across your github tutorial),
Under "Connecting to the Internet", they mentioned the motion_start_wrapper.sh script
however i do not have this specified file at all. 

I managed to execute everything correct only until "Connecting to the Internet", can you guide me what did i do wrong?

**Comment by alext-mkrs** [comment]
Oh, how interesting - that article looks to be based on this project, but a bit reworked (no GPIO triggering and no Xively upload, but with GMail, audio playback and Edison cutout, with Twitter and GDrive scripts as well as some of the instructions directly taken from here as-is) and without any attribution.

`motion_start_wrapper.sh` is from my project again, so that on the motion event start there are several things executed at once - but they seem to have replaced it with only one action without removing the reference to the script.

Well, specific problem you face when connecting would help me to suggest something more meaningful than "check out Temboo instructions - they are really simple and step-by-step". Check out [my Instructables post](http://www.instructables.com/id/Edison-monitoring-system-with-motion-detection-and/?ALLSTEPS) on this project, maybe it will be of help (though I specifically not go through those steps as time goes by and Teboo SDK and Choreos change).

**Comment by mrcrocodile556** [comment]
Thank you!
